version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docs

  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
