"""Self-contained geometry-node utility groups for the modifiers
panel, rebuilt from data specs (no external node libraries needed).

Ported node-graph logic:
- mesh curvature: cotangent-Laplacian mean curvature per vertex (plus
  gaussian / signed / unsigned edge angle outputs); NOTE the Mean
  Curvature output is the raw |Laplacian| — divide by 2x vertex area
  for a density-independent 1/m value
- mesh ambient occlusion: hemisphere raycast AO baked into a named
  attribute (inputs: Rays Samples, Rays Angle Offset, Seed, Blur
  Iterations, Attribute)

The specs are verbatim graph serializations; _build_from_spec turns one
into a node group. Group version bumps force a rebuild on next use.
"""

import bpy

LIB_VERSION = 4

CURVATURE_GROUP = "iOps_MeshCurvature"
AO_GROUP = "iOps_MeshAO"

# Human-readable labels for the semantic blocks; everything else gets
# an automatic label from its operation.
_CURVATURE_LABELS = {
    "Offset Corner in Face": "Prev Corner",
    "Offset Corner in Face.001": "Next Corner",
    "Evaluate at Index.001": "Prev Corner Position",
    "Evaluate at Index.002": "Next Corner Position",
    "Vector Math": "Vec to Prev Corner",
    "Vector Math.001": "Vec to Next Corner",
    "Vector Math.005": "Cos Corner Angle",
    "Math.003": "Corner Angle",
    "Evaluate on Domain.001": "Corner Angle -> Point",
    "Math.004": "Sum Corner Angles",
    "Math.005": "Angle Defect (Gaussian)",
    "Offset Corner in Face.002": "Alpha Prev Corner",
    "Offset Corner in Face.003": "Alpha Next Corner",
    "Offset Corner in Face.004": "Beta Opposite Corner",
    "Math.002": "Alpha Angle",
    "Math.008": "Beta Angle",
    "Math.010": "Tan Alpha",
    "Math.011": "Cot Alpha",
    "Math.012": "Tan Beta",
    "Math.013": "Cot Beta",
    "Math.014": "Cot Weight (a+b)",
    "Vector Math.017": "Corner Edge Vector",
    "Vector Math.018": "Cot-Weighted Edge",
    "Evaluate on Domain.002": "Weighted Edges -> Corner",
    "Vector Math.019": "Laplacian Sum",
    "Vector Math.020": "Mean Curvature |Laplacian|",
    "Edge Vertices": "Edge Vertices",
    "Vector Math.024": "Normal Delta (V2-V1)",
    "Vector Math.025": "Edge Vector",
    "Vector Math.026": "Bend Sign (dot)",
    "Evaluate on Domain.003": "Signed Angle -> Edge",
    "Math": "Unsigned Angle",
    "Corners of Edge": "Corner of Edge A",
    "Corners of Edge.001": "Corner of Edge B",
    "Switch": "Pick Opposite Corner",
    "Compare": "Same Corner?",
}

_AO_LABELS = {
    "Duplicate Elements.001": "Duplicate Points per Ray",
    "Random Value": "Random Ray Direction",
    "Rotate Vector": "Spread Ray in Cone",
    "Raycast": "Occlusion Raycast",
    "Accumulate Field": "Sum Hits per Point",
    "Math": "Hits / Samples",
    "Map Range": "To AO 0..1",
    "Blur Attribute": "Blur AO",
    "Store Named Attribute": "Bake AO Attribute",
    "Attribute Statistic": "Source Point Count",
    "Sample Index": "Read AO at Source Point",
    "Capture Attribute.001": "Capture Ray Direction",
    "Join Geometry": "Join External Occluders",
    "Switch": "Use External Mesh?",
}


def _auto_label(node):
    op = getattr(node, "operation", None)
    if op:
        return op.replace("_", " ").title()
    domain = getattr(node, "domain", None)
    if domain and node.bl_idname in {"GeometryNodeFieldOnDomain",
                                     "GeometryNodeFieldAtIndex",
                                     "GeometryNodeCaptureAttribute",
                                     "GeometryNodeBlurAttribute",
                                     "GeometryNodeStoreNamedAttribute",
                                     "GeometryNodeSampleIndex",
                                     "GeometryNodeAccumulateField",
                                     "GeometryNodeAttributeStatistic"}:
        base = node.bl_idname.replace("GeometryNode", "")
        return f"{base} [{domain}]"
    return ""


def _build_from_spec(name, spec, labels=None):
    ng = bpy.data.node_groups.new(name, "GeometryNodeTree")
    iface = ng.interface
    gi_idents = []  # spec identifier -> position among INPUT sockets
    go_idents = []
    for s in spec["sockets"]:
        sock = iface.new_socket(s["name"], in_out=s["in_out"],
                                socket_type=s["type"])
        (gi_idents if s["in_out"] == "INPUT" else go_idents).append(s["ident"])
        for key, attr in (("default", "default_value"),
                          ("min_value", "min_value"),
                          ("max_value", "max_value"),
                          ("subtype", "subtype")):
            v = s.get(key)
            if v is None:
                continue
            try:
                setattr(sock, attr, v)
            except (AttributeError, TypeError, ValueError):
                pass
    nodes = {}
    io_nodes = {"GI": None, "GO": None}
    for nd in spec["nodes"]:
        n = ng.nodes.new(nd["idname"])
        n.name = nd["name"]
        n.location = nd["loc"]
        if nd["idname"] == "NodeGroupInput":
            io_nodes["GI"] = n
        elif nd["idname"] == "NodeGroupOutput":
            io_nodes["GO"] = n
        # props first: data_type/operation/domain change the socket
        # layout, and defaults/links below address sockets by index
        for key, v in nd.get("props", {}).items():
            try:
                setattr(n, key, v)
            except (AttributeError, TypeError, ValueError):
                pass
        for dt, iname in nd.get("capture_items", ()):
            # item data_type -> socket_type enum
            socket_type = {"FLOAT_VECTOR": "VECTOR", "FLOAT_COLOR": "RGBA",
                           "QUATERNION": "ROTATION",
                           "FLOAT4X4": "MATRIX"}.get(dt, dt)
            n.capture_items.new(socket_type, iname)
        for i, v in nd.get("input_defaults", ()):
            try:
                n.inputs[i].default_value = v
            except (IndexError, AttributeError, TypeError, ValueError):
                pass
        n.label = (labels or {}).get(nd["name"]) or _auto_label(n)
        nodes[nd["name"]] = n
    for src, dst in spec["links"]:
        if src[0] == "GI":
            out_sock = io_nodes["GI"].outputs[gi_idents.index(src[1])]
        else:
            out_sock = nodes[src[0]].outputs[src[1]]
        if dst[0] == "GO":
            in_sock = io_nodes["GO"].inputs[go_idents.index(dst[1])]
        else:
            in_sock = nodes[dst[0]].inputs[dst[1]]
        ng.links.new(out_sock, in_sock)
    ng["iops_gn_lib_version"] = LIB_VERSION
    return ng


def _ensure(name, spec, labels=None):
    ng = bpy.data.node_groups.get(name)
    if ng is not None:
        if ng.get("iops_gn_lib_version") == LIB_VERSION:
            return ng
        ng.name += "_old"
    return _build_from_spec(name, spec, labels)


def ensure_mesh_curvature():
    """Field group, no geometry flow: outputs Gaussian Curvature, Mean
    Curvature (raw |cotan Laplacian|), Angle Signed/Unsigned."""
    return _ensure(CURVATURE_GROUP, _CURVATURE_SPEC, _CURVATURE_LABELS)


def ensure_mesh_ao():
    """Geometry-through group: bakes hemisphere-raycast AO into the
    attribute named by its 'Attribute' input; also outputs the AO
    field directly."""
    return _ensure(AO_GROUP, _AO_SPEC, _AO_LABELS)


_CURVATURE_SPEC = {'sockets': [{'name': 'Angle Unsigned',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Socket_1',
              'default': 0.0,
              'min_value': -3.4028234663852886e+38,
              'max_value': 3.4028234663852886e+38,
              'subtype': 'NONE'},
             {'name': 'Angle Signed',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Socket_0',
              'default': 0.0,
              'min_value': -3.4028234663852886e+38,
              'max_value': 3.4028234663852886e+38,
              'subtype': 'NONE'},
             {'name': 'Gaussian Curvature',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Socket_2',
              'default': 0.0,
              'min_value': -3.4028234663852886e+38,
              'max_value': 3.4028234663852886e+38,
              'subtype': 'NONE'},
             {'name': 'Mean Curvature',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Socket_3',
              'default': 0.0,
              'min_value': -3.4028234663852886e+38,
              'max_value': 3.4028234663852886e+38,
              'subtype': 'NONE'}],
 'nodes': [{'name': 'Group Output',
            'idname': 'NodeGroupOutput',
            'loc': [3880, -380],
            'props': {'hide': False, 'is_active_output': True}},
           {'name': 'Group Input',
            'idname': 'NodeGroupInput',
            'loc': [700, -440],
            'props': {'hide': False}},
           {'name': 'Evaluate at Index.001',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [1980, -360],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Evaluate at Index.002',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [1980, -520],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Position',
            'idname': 'GeometryNodeInputPosition',
            'loc': [1760, -540],
            'props': {'hide': False}},
           {'name': 'Vector Math',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2160, -360],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.001',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2160, -520],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Offset Corner in Face',
            'idname': 'GeometryNodeOffsetCornerInFace',
            'loc': [1760, -400],
            'props': {'hide': False},
            'input_defaults': [[0, 0], [1, -1]]},
           {'name': 'Offset Corner in Face.001',
            'idname': 'GeometryNodeOffsetCornerInFace',
            'loc': [1760, -620],
            'props': {'hide': False},
            'input_defaults': [[0, 0], [1, 1]]},
           {'name': 'Vector Math.005',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2520, -400],
            'props': {'hide': False, 'operation': 'DOT_PRODUCT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.004',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2340, -360],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Vector Math.006',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2340, -520],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Math.003',
            'idname': 'ShaderNodeMath',
            'loc': [2700, -400],
            'props': {'hide': False,
                      'operation': 'ARCCOSINE',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]},
           {'name': 'Math.004',
            'idname': 'ShaderNodeMath',
            'loc': [3060, -400],
            'props': {'hide': False,
                      'operation': 'MULTIPLY',
                      'use_clamp': False},
            'input_defaults': [[2, 0.5]]},
           {'name': 'Evaluate on Domain.001',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [2880, -400],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT'}},
           {'name': 'Vertex Neighbors.001',
            'idname': 'GeometryNodeInputMeshVertexNeighbors',
            'loc': [2880, -560],
            'props': {'hide': False}},
           {'name': 'Math.005',
            'idname': 'ShaderNodeMath',
            'loc': [3240, -400],
            'props': {'hide': False,
                      'operation': 'SUBTRACT',
                      'use_clamp': False},
            'input_defaults': [[0, 6.2831854820251465], [2, 0.5]]},
           {'name': 'Evaluate at Index.003',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [1220, -960],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Position.001',
            'idname': 'GeometryNodeInputPosition',
            'loc': [800, -1100],
            'props': {'hide': False}},
           {'name': 'Vector Math.007',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1420, -880],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Offset Corner in Face.002',
            'idname': 'GeometryNodeOffsetCornerInFace',
            'loc': [1020, -960],
            'props': {'hide': False},
            'input_defaults': [[0, 0], [1, -1]]},
           {'name': 'Vector Math.008',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1420, -1020],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Evaluate at Index.004',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [1220, -1140],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Offset Corner in Face.003',
            'idname': 'GeometryNodeOffsetCornerInFace',
            'loc': [1020, -1180],
            'props': {'hide': False},
            'input_defaults': [[0, 0], [1, 1]]},
           {'name': 'Vector Math.009',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1600, -880],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Vector Math.010',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1600, -1020],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Vector Math.011',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1780, -920],
            'props': {'hide': False, 'operation': 'DOT_PRODUCT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Math.002',
            'idname': 'ShaderNodeMath',
            'loc': [1960, -920],
            'props': {'hide': False,
                      'operation': 'ARCCOSINE',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]},
           {'name': 'Edges of Corner',
            'idname': 'GeometryNodeEdgesOfCorner',
            'loc': [260, -1500],
            'props': {'hide': False},
            'input_defaults': [[0, 0]]},
           {'name': 'Corners of Edge',
            'idname': 'GeometryNodeCornersOfEdge',
            'loc': [460, -1420],
            'props': {'hide': False},
            'input_defaults': [[1, 0.0], [2, 0]]},
           {'name': 'Index',
            'idname': 'GeometryNodeInputIndex',
            'loc': [460, -1340],
            'props': {'hide': False}},
           {'name': 'Compare',
            'idname': 'FunctionNodeCompare',
            'loc': [640, -1280],
            'props': {'hide': False,
                      'operation': 'EQUAL',
                      'data_type': 'INT',
                      'mode': 'ELEMENT'}},
           {'name': 'Switch',
            'idname': 'GeometryNodeSwitch',
            'loc': [820, -1340],
            'props': {'hide': False, 'input_type': 'INT'}},
           {'name': 'Corners of Edge.001',
            'idname': 'GeometryNodeCornersOfEdge',
            'loc': [460, -1580],
            'props': {'hide': False},
            'input_defaults': [[1, 0.0], [2, 1]]},
           {'name': 'Offset Corner in Face.004',
            'idname': 'GeometryNodeOffsetCornerInFace',
            'loc': [1020, -1320],
            'props': {'hide': False},
            'input_defaults': [[1, 2]]},
           {'name': 'Evaluate at Index.005',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [1220, -1340],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Vector Math.012',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1420, -1180],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.013',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1420, -1320],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.014',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1600, -1140],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Vector Math.015',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1600, -1260],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Vector Math.016',
            'idname': 'ShaderNodeVectorMath',
            'loc': [1780, -1120],
            'props': {'hide': False, 'operation': 'DOT_PRODUCT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Math.008',
            'idname': 'ShaderNodeMath',
            'loc': [1960, -1100],
            'props': {'hide': False,
                      'operation': 'ARCCOSINE',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]},
           {'name': 'Math.010',
            'idname': 'ShaderNodeMath',
            'loc': [2140, -920],
            'props': {'hide': False,
                      'operation': 'TANGENT',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]},
           {'name': 'Math.011',
            'idname': 'ShaderNodeMath',
            'loc': [2320, -920],
            'props': {'hide': False,
                      'operation': 'DIVIDE',
                      'use_clamp': False},
            'input_defaults': [[0, 1.0], [2, 0.5]]},
           {'name': 'Math.012',
            'idname': 'ShaderNodeMath',
            'loc': [2140, -1100],
            'props': {'hide': False,
                      'operation': 'TANGENT',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]},
           {'name': 'Math.013',
            'idname': 'ShaderNodeMath',
            'loc': [2320, -1100],
            'props': {'hide': False,
                      'operation': 'DIVIDE',
                      'use_clamp': False},
            'input_defaults': [[0, 1.0], [2, 0.5]]},
           {'name': 'Math.014',
            'idname': 'ShaderNodeMath',
            'loc': [2500, -920],
            'props': {'hide': False,
                      'operation': 'ADD',
                      'use_clamp': False},
            'input_defaults': [[2, 0.5]]},
           {'name': 'Vector Math.017',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2500, -760],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.018',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2680, -760],
            'props': {'hide': False, 'operation': 'SCALE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]], [2, [0.0, 0.0, 0.0]]]},
           {'name': 'Evaluate on Domain.002',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [2860, -760],
            'props': {'hide': False,
                      'domain': 'CORNER',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Vector Math.019',
            'idname': 'ShaderNodeVectorMath',
            'loc': [3040, -760],
            'props': {'hide': False, 'operation': 'SCALE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]], [2, [0.0, 0.0, 0.0]]]},
           {'name': 'Vertex Neighbors.002',
            'idname': 'GeometryNodeInputMeshVertexNeighbors',
            'loc': [2860, -900],
            'props': {'hide': False}},
           {'name': 'Vector Math.020',
            'idname': 'ShaderNodeVectorMath',
            'loc': [3220, -760],
            'props': {'hide': False, 'operation': 'LENGTH'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Edge Vertices',
            'idname': 'GeometryNodeInputMeshEdgeVertices',
            'loc': [2140, 0],
            'props': {'hide': False}},
           {'name': 'Vector Math.024',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2680, 120],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Evaluate at Index',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [2440, 40],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Normal',
            'idname': 'GeometryNodeInputNormal',
            'loc': [2140, -140],
            'props': {'hide': False, 'legacy_corner_normals': True}},
           {'name': 'Evaluate at Index.006',
            'idname': 'GeometryNodeFieldAtIndex',
            'loc': [2440, 200],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT_VECTOR'}},
           {'name': 'Vector Math.025',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2440, -140],
            'props': {'hide': False, 'operation': 'SUBTRACT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.026',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2860, 80],
            'props': {'hide': False, 'operation': 'DOT_PRODUCT'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Evaluate on Domain.003',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [3040, 80],
            'props': {'hide': False,
                      'domain': 'EDGE',
                      'data_type': 'FLOAT'}},
           {'name': 'Vector Math.023',
            'idname': 'ShaderNodeVectorMath',
            'loc': [2680, -40],
            'props': {'hide': False, 'operation': 'NORMALIZE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 1.0]]},
           {'name': 'Evaluate on Domain',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [3420, -400],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT'}},
           {'name': 'Evaluate on Domain.004',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [3400, -760],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT'}},
           {'name': 'Evaluate on Domain.005',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [3400, 20],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT'}},
           {'name': 'Evaluate on Domain.006',
            'idname': 'GeometryNodeFieldOnDomain',
            'loc': [3400, 160],
            'props': {'hide': False,
                      'domain': 'POINT',
                      'data_type': 'FLOAT'}},
           {'name': 'Math',
            'idname': 'ShaderNodeMath',
            'loc': [3220, 160],
            'props': {'hide': False,
                      'operation': 'ABSOLUTE',
                      'use_clamp': False},
            'input_defaults': [[1, 0.5], [2, 0.5]]}],
 'links': [[['Evaluate on Domain.002', 0], ['Vector Math.019', 0]],
           [['Vector Math.018', 0], ['Evaluate on Domain.002', 0]],
           [['Index', 0], ['Compare', 0]],
           [['Evaluate at Index.004', 0], ['Vector Math.013', 0]],
           [['Position.001', 0], ['Evaluate at Index.003', 0]],
           [['Evaluate at Index.005', 0], ['Vector Math.012', 1]],
           [['Vector Math.012', 0], ['Vector Math.014', 0]],
           [['Offset Corner in Face.004', 0], ['Evaluate at Index.005', 1]],
           [['Vertex Neighbors.001', 0], ['Math.004', 1]],
           [['Corners of Edge', 0], ['Compare', 1]],
           [['Vertex Neighbors.002', 0], ['Vector Math.019', 3]],
           [['Edge Vertices', 0], ['Evaluate at Index', 1]],
           [['Math.004', 0], ['Math.005', 1]],
           [['Offset Corner in Face.001', 0], ['Evaluate at Index.002', 1]],
           [['Corners of Edge.001', 0], ['Switch', 2]],
           [['Position.001', 0], ['Vector Math.007', 0]],
           [['Vector Math.006', 0], ['Vector Math.005', 1]],
           [['Compare', 0], ['Switch', 0]],
           [['Evaluate at Index', 0], ['Vector Math.024', 1]],
           [['Normal', 0], ['Evaluate at Index.006', 0]],
           [['Math.002', 0], ['Math.010', 0]],
           [['Evaluate at Index.004', 0], ['Vector Math.008', 0]],
           [['Evaluate at Index.003', 0], ['Vector Math.007', 1]],
           [['Position', 0], ['Vector Math.001', 0]],
           [['Edge Vertices', 2], ['Vector Math.025', 1]],
           [['Switch', 0], ['Offset Corner in Face.004', 0]],
           [['Position', 0], ['Evaluate at Index.002', 0]],
           [['Vector Math.017', 0], ['Vector Math.018', 0]],
           [['Evaluate at Index.001', 0], ['Vector Math', 1]],
           [['Evaluate at Index.005', 0], ['Vector Math.013', 1]],
           [['Offset Corner in Face', 0], ['Evaluate at Index.001', 1]],
           [['Vector Math.019', 0], ['Vector Math.020', 0]],
           [['Edges of Corner', 0], ['Corners of Edge.001', 0]],
           [['Vector Math.007', 0], ['Vector Math.009', 0]],
           [['Math.003', 0], ['Evaluate on Domain.001', 0]],
           [['Vector Math.005', 1], ['Math.003', 0]],
           [['Position.001', 0], ['Vector Math.017', 1]],
           [['Vector Math.004', 0], ['Vector Math.005', 0]],
           [['Evaluate on Domain.001', 0], ['Math.004', 0]],
           [['Vector Math.023', 0], ['Vector Math.026', 1]],
           [['Position.001', 0], ['Vector Math.012', 0]],
           [['Math.011', 0], ['Math.014', 0]],
           [['Vector Math.001', 0], ['Vector Math.006', 0]],
           [['Edge Vertices', 3], ['Vector Math.025', 0]],
           [['Vector Math', 0], ['Vector Math.004', 0]],
           [['Offset Corner in Face.003', 0], ['Evaluate at Index.004', 1]],
           [['Edges of Corner', 0], ['Corners of Edge', 0]],
           [['Vector Math.026', 1], ['Evaluate on Domain.003', 0]],
           [['Math.012', 0], ['Math.013', 1]],
           [['Vector Math.015', 0], ['Vector Math.016', 1]],
           [['Vector Math.010', 0], ['Vector Math.011', 1]],
           [['Evaluate at Index.002', 0], ['Vector Math.001', 1]],
           [['Math.008', 0], ['Math.012', 0]],
           [['Evaluate at Index.003', 0], ['Vector Math.008', 1]],
           [['Math.014', 0], ['Vector Math.018', 3]],
           [['Edge Vertices', 1], ['Evaluate at Index.006', 1]],
           [['Evaluate at Index.006', 0], ['Vector Math.024', 0]],
           [['Vector Math.009', 0], ['Vector Math.011', 0]],
           [['Evaluate at Index.004', 0], ['Vector Math.017', 0]],
           [['Evaluate on Domain.003', 0], ['Evaluate on Domain.005', 0]],
           [['Vector Math.008', 0], ['Vector Math.010', 0]],
           [['Math.013', 0], ['Math.014', 1]],
           [['Normal', 0], ['Evaluate at Index', 0]],
           [['Position.001', 0], ['Evaluate at Index.004', 0]],
           [['Vector Math.016', 1], ['Math.008', 0]],
           [['Vector Math.011', 1], ['Math.002', 0]],
           [['Position', 0], ['Vector Math', 0]],
           [['Offset Corner in Face.002', 0], ['Evaluate at Index.003', 1]],
           [['Corners of Edge', 0], ['Switch', 1]],
           [['Vector Math.020', 1], ['Evaluate on Domain.004', 0]],
           [['Math.010', 0], ['Math.011', 1]],
           [['Vector Math.024', 0], ['Vector Math.026', 0]],
           [['Position', 0], ['Evaluate at Index.001', 0]],
           [['Vector Math.025', 0], ['Vector Math.023', 0]],
           [['Vector Math.013', 0], ['Vector Math.015', 0]],
           [['Math.005', 0], ['Evaluate on Domain', 0]],
           [['Vector Math.014', 0], ['Vector Math.016', 0]],
           [['Evaluate on Domain.005', 0], ['GO', 'Socket_0']],
           [['Evaluate on Domain.003', 0], ['Math', 0]],
           [['Math', 0], ['Evaluate on Domain.006', 0]],
           [['Evaluate on Domain.006', 0], ['GO', 'Socket_1']],
           [['Evaluate on Domain', 0], ['GO', 'Socket_2']],
           [['Evaluate on Domain.004', 0], ['GO', 'Socket_3']],
           [['Position.001', 0], ['Evaluate at Index.005', 0]]]}

_AO_SPEC = {'sockets': [{'name': 'Mesh',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketGeometry',
              'ident': 'Output_1',
              'default': None},
             {'name': 'AO',
              'in_out': 'OUTPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Socket_0',
              'default': 0.0,
              'min_value': -3.4028234663852886e+38,
              'max_value': 3.4028234663852886e+38,
              'subtype': 'NONE'},
             {'name': 'Mesh',
              'in_out': 'INPUT',
              'type': 'NodeSocketGeometry',
              'ident': 'Input_0',
              'default': None},
             {'name': 'Rays Samples',
              'in_out': 'INPUT',
              'type': 'NodeSocketInt',
              'ident': 'Input_3',
              'default': 20,
              'min_value': 1,
              'max_value': 200,
              'subtype': 'NONE'},
             {'name': 'Rays Angle Offset',
              'in_out': 'INPUT',
              'type': 'NodeSocketFloat',
              'ident': 'Input_4',
              'default': 1.0471975803375244,
              'max_value': 3.1415927410125732,
              'subtype': 'ANGLE'},
             {'name': 'Seed',
              'in_out': 'INPUT',
              'type': 'NodeSocketInt',
              'ident': 'Input_5',
              'default': 0,
              'min_value': -10000,
              'max_value': 10000,
              'subtype': 'NONE'},
             {'name': 'Blur Iterations',
              'in_out': 'INPUT',
              'type': 'NodeSocketInt',
              'ident': 'Input_8',
              'default': 2,
              'max_value': 2147483647,
              'subtype': 'NONE'},
             {'name': 'External Mesh',
              'in_out': 'INPUT',
              'type': 'NodeSocketBool',
              'ident': 'Input_10',
              'default': False},
             {'name': 'External Mesh',
              'in_out': 'INPUT',
              'type': 'NodeSocketGeometry',
              'ident': 'Input_9',
              'default': None},
             {'name': 'Attribute',
              'in_out': 'INPUT',
              'type': 'NodeSocketString',
              'ident': 'Input_7',
              'default': 'ao',
              'subtype': 'NONE'}],
 'nodes': [{'name': 'Accumulate Field.001',
            'idname': 'GeometryNodeAccumulateField',
            'loc': [-140, 60],
            'props': {'hide': False,
                      'data_type': 'FLOAT',
                      'domain': 'POINT'}},
           {'name': 'Math.005',
            'idname': 'ShaderNodeMath',
            'loc': [80, 60],
            'props': {'hide': False,
                      'operation': 'DIVIDE',
                      'use_clamp': False},
            'input_defaults': [[2, 0.5]]},
           {'name': 'Index.003',
            'idname': 'GeometryNodeInputIndex',
            'loc': [-580, -260],
            'props': {'hide': False}},
           {'name': 'Random Value.003',
            'idname': 'FunctionNodeRandomValue',
            'loc': [-1060, -240],
            'props': {'hide': False, 'data_type': 'FLOAT_VECTOR'},
            'input_defaults': [[2, 0]]},
           {'name': 'Vector Math.004',
            'idname': 'ShaderNodeVectorMath',
            'loc': [-840, 60],
            'props': {'hide': False, 'operation': 'ADD'},
            'input_defaults': [[2, [0.0, 0.0, 0.0]], [3, 1.0]]},
           {'name': 'Vector Math.005',
            'idname': 'ShaderNodeVectorMath',
            'loc': [-1060, 20],
            'props': {'hide': False, 'operation': 'SCALE'},
            'input_defaults': [[1, [0.0, 0.0, 0.0]],
                               [2, [0.0, 0.0, 0.0]],
                               [3, 9.999999747378752e-06]]},
           {'name': 'Duplicate Elements.001',
            'idname': 'GeometryNodeDuplicateElements',
            'loc': [-140, 260],
            'props': {'hide': False, 'domain': 'POINT'},
            'input_defaults': [[1, True]]},
           {'name': 'Position.001',
            'idname': 'GeometryNodeInputPosition',
            'loc': [-1060, 100],
            'props': {'hide': False}},
           {'name': 'Raycast.001',
            'idname': 'GeometryNodeRaycast',
            'loc': [-580, 140],
            'props': {'hide': False, 'data_type': 'FLOAT'},
            'input_defaults': [[1, 0.0], [2, 'Interpolated'], [5, 100.0]]},
           {'name': 'Capture Attribute.001',
            'idname': 'GeometryNodeCaptureAttribute',
            'loc': [-1320, 200],
            'props': {'hide': False, 'domain': 'POINT'},
            'capture_items': [['FLOAT_VECTOR', 'Value']],
            'input_defaults': [[1, True]]},
           {'name': 'Normal.001',
            'idname': 'GeometryNodeInputNormal',
            'loc': [-1540, 140],
            'props': {'hide': False, 'legacy_corner_normals': True}},
           {'name': 'Attribute Statistic',
            'idname': 'GeometryNodeAttributeStatistic',
            'loc': [620, 220],
            'props': {'hide': False,
                      'data_type': 'FLOAT',
                      'domain': 'POINT'},
            'input_defaults': [[1, True]]},
           {'name': 'Sample Index',
            'idname': 'GeometryNodeSampleIndex',
            'loc': [380, 300],
            'props': {'hide': False,
                      'data_type': 'FLOAT',
                      'domain': 'POINT',
                      'clamp': True}},
           {'name': 'Store Named Attribute',
            'idname': 'GeometryNodeStoreNamedAttribute',
            'loc': [1240, 480],
            'props': {'hide': False,
                      'data_type': 'FLOAT',
                      'domain': 'POINT'},
            'input_defaults': [[1, True]]},
           {'name': 'Group Output',
            'idname': 'NodeGroupOutput',
            'loc': [1500, 420],
            'props': {'hide': False, 'is_active_output': True}},
           {'name': 'Blur Attribute',
            'idname': 'GeometryNodeBlurAttribute',
            'loc': [1040, 300],
            'props': {'hide': False, 'data_type': 'FLOAT'},
            'input_defaults': [[2, 1.0]]},
           {'name': 'Math',
            'idname': 'ShaderNodeMath',
            'loc': [-1260, -240],
            'props': {'hide': False,
                      'operation': 'MULTIPLY',
                      'use_clamp': False},
            'input_defaults': [[1, -1.0], [2, 0.5]]},
           {'name': 'Map Range',
            'idname': 'ShaderNodeMapRange',
            'loc': [820, 300],
            'props': {'hide': False,
                      'clamp': True,
                      'interpolation_type': 'LINEAR',
                      'data_type': 'FLOAT'},
            'input_defaults': [[3, 0.0],
                               [4, 1.0],
                               [5, 4.0],
                               [6, [0.0, 0.0, 0.0]],
                               [7, [0.0, 0.0, 0.0]],
                               [8, [1.0, 1.0, 1.0]],
                               [9, [0.0, 0.0, 0.0]],
                               [10, [1.0, 1.0, 1.0]],
                               [11, [4.0, 4.0, 4.0]]]},
           {'name': 'Group Input',
            'idname': 'NodeGroupInput',
            'loc': [-2500, 340],
            'props': {'hide': False}},
           {'name': 'Join Geometry',
            'idname': 'GeometryNodeJoinGeometry',
            'loc': [-1960, -20],
            'props': {'hide': False}},
           {'name': 'Switch',
            'idname': 'GeometryNodeSwitch',
            'loc': [-1760, 80],
            'props': {'hide': False, 'input_type': 'GEOMETRY'}},
           {'name': 'Rotate Vector',
            'idname': 'FunctionNodeRotateVector',
            'loc': [-840, -180],
            'props': {'hide': False}},
           {'name': 'Integer Math',
            'idname': 'FunctionNodeIntegerMath',
            'loc': [-340, -140],
            'props': {'hide': False, 'operation': 'DIVIDE_FLOOR'},
            'input_defaults': [[2, 0]]},
           {'name': 'Integer Math.001',
            'idname': 'FunctionNodeIntegerMath',
            'loc': [80, -120],
            'props': {'hide': False, 'operation': 'MULTIPLY'},
            'input_defaults': [[2, 0]]},
           {'name': 'Named Attribute',
            'idname': 'GeometryNodeInputNamedAttribute',
            'loc': [1040, 160],
            'props': {'hide': False, 'data_type': 'FLOAT'}}],
 'links': [[['Switch', 0], ['Raycast.001', 0]],
           [['Duplicate Elements.001', 0], ['Sample Index', 0]],
           [['Capture Attribute.001', 0], ['Duplicate Elements.001', 0]],
           [['GI', 'Input_0'], ['Capture Attribute.001', 0]],
           [['Position.001', 0], ['Vector Math.004', 0]],
           [['Vector Math.005', 0], ['Vector Math.004', 1]],
           [['Capture Attribute.001', 2], ['Vector Math.005', 0]],
           [['Vector Math.004', 0], ['Raycast.001', 3]],
           [['GI', 'Input_3'], ['Duplicate Elements.001', 2]],
           [['Math.005', 0], ['Sample Index', 1]],
           [['Raycast.001', 3], ['Accumulate Field.001', 0]],
           [['Accumulate Field.001', 2], ['Math.005', 0]],
           [['GI', 'Input_3'], ['Math.005', 1]],
           [['Integer Math', 0], ['Accumulate Field.001', 1]],
           [['Integer Math.001', 0], ['Sample Index', 2]],
           [['Store Named Attribute', 0], ['GO', 'Output_1']],
           [['GI', 'Input_4'], ['Math', 0]],
           [['Math', 0], ['Random Value.003', 0]],
           [['GI', 'Input_4'], ['Random Value.003', 1]],
           [['GI', 'Input_5'], ['Random Value.003', 3]],
           [['GI', 'Input_0'], ['Attribute Statistic', 0]],
           [['Sample Index', 0], ['Attribute Statistic', 2]],
           [['Attribute Statistic', 3], ['Map Range', 1]],
           [['Attribute Statistic', 4], ['Map Range', 2]],
           [['Sample Index', 0], ['Map Range', 0]],
           [['GI', 'Input_0'], ['Store Named Attribute', 0]],
           [['Blur Attribute', 0], ['Store Named Attribute', 3]],
           [['GI', 'Input_7'], ['Store Named Attribute', 2]],
           [['GI', 'Input_8'], ['Blur Attribute', 1]],
           [['Map Range', 0], ['Blur Attribute', 0]],
           [['GI', 'Input_0'], ['Switch', 1]],
           [['GI', 'Input_0'], ['Join Geometry', 0]],
           [['GI', 'Input_9'], ['Join Geometry', 0]],
           [['Join Geometry', 0], ['Switch', 2]],
           [['GI', 'Input_10'], ['Switch', 0]],
           [['Normal.001', 1], ['Capture Attribute.001', 2]],
           [['Capture Attribute.001', 2], ['Rotate Vector', 0]],
           [['Random Value.003', 0], ['Rotate Vector', 1]],
           [['Rotate Vector', 0], ['Raycast.001', 4]],
           [['Index.003', 0], ['Integer Math', 0]],
           [['GI', 'Input_3'], ['Integer Math', 1]],
           [['GI', 'Input_3'], ['Integer Math.001', 0]],
           [['Index.003', 0], ['Integer Math.001', 1]],
           [['GI', 'Input_7'], ['Named Attribute', 0]],
           [['Named Attribute', 0], ['GO', 'Socket_0']]]}
