"""Native modifier panel layouts, GENERATED from Blender's
source/blender/modifiers/intern/MOD_*.cc (branch blender-v5.2-release)
by the gen_layouts.py scratch script - do not hand-edit; regenerate.

LAYOUTS[md.type] = [panel, ...] in native order. panel = {
    "id": subpanel idname ("" = the root body), "label", "parent": id | None,
    "header": [prop, ...]     # checkbox props drawn in the subpanel header
    "items": [{"prop": name, "expand"?, "slider"?, "text"?}
              | {"vgroup": name, "invert"?: name}
              | {"sep": True} | {"heading": text}, ...]
}
Props are listed unconditionally (the C code hides some behind
enum checks); the reader draws only those that exist on the modifier.
"""

LAYOUTS = {'ARMATURE': [{'id': '',
               'label': '',
               'parent': None,
               'items': [{'prop': 'object'},
                         {'vgroup': 'vertex_group',
                          'invert': 'invert_vertex_group'},
                         {'prop': 'use_deform_preserve_volume'},
                         {'prop': 'use_multi_modifier'},
                         {'heading': 'Bind To'},
                         {'prop': 'use_vertex_groups',
                          'text': 'Vertex Groups'},
                         {'prop': 'use_bone_envelopes',
                          'text': 'Bone Envelopes'}]}],
 'ARRAY': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'fit_type'},
                      {'prop': 'count'},
                      {'prop': 'fit_length'},
                      {'prop': 'curve'}]},
           {'id': 'relative_offset',
            'label': '',
            'parent': None,
            'items': [{'prop': 'relative_offset_displace', 'text': 'Factor'}],
            'header': ['use_relative_offset']},
           {'id': 'constant_offset',
            'label': '',
            'parent': None,
            'items': [{'prop': 'constant_offset_displace',
                       'text': 'Distance'}],
            'header': ['use_constant_offset']},
           {'id': 'object_offset',
            'label': '',
            'parent': None,
            'items': [{'prop': 'offset_object', 'text': 'Object'}],
            'header': ['use_object_offset']},
           {'id': 'merge',
            'label': '',
            'parent': None,
            'items': [{'prop': 'merge_threshold', 'text': 'Distance'},
                      {'prop': 'use_merge_vertices_cap',
                       'text': 'First and Last Copies'}],
            'header': ['use_merge_vertices']},
           {'id': 'uv',
            'label': 'UVs',
            'parent': None,
            'items': [{'prop': 'offset_u',
                       'expand': True,
                       'text': 'Offset U'},
                      {'prop': 'offset_v', 'expand': True, 'text': 'V'}]},
           {'id': 'caps',
            'label': 'Caps',
            'parent': None,
            'items': [{'prop': 'start_cap', 'text': 'Cap Start'},
                      {'prop': 'end_cap', 'text': 'End'}]}],
 'BEVEL': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'affect', 'expand': True},
                      {'prop': 'offset_type'},
                      {'prop': 'width_pct'},
                      {'prop': 'width', 'text': 'Amount'},
                      {'prop': 'segments'},
                      {'sep': True},
                      {'prop': 'limit_method'},
                      {'prop': 'angle_limit'},
                      {'prop': 'edge_weight'},
                      {'prop': 'vertex_weight'},
                      {'vgroup': 'vertex_group',
                       'invert': 'invert_vertex_group'}]},
           {'id': 'profile',
            'label': 'Profile',
            'parent': None,
            'items': [{'prop': 'profile_type', 'expand': True},
                      {'prop': 'profile', 'slider': True, 'text': 'Shape'},
                      {'prop': 'custom_profile'}]},
           {'id': 'geometry',
            'label': 'Geometry',
            'parent': None,
            'items': [{'prop': 'miter_outer', 'text': 'Miter Outer'},
                      {'prop': 'miter_inner', 'text': 'Inner'},
                      {'prop': 'spread'},
                      {'sep': True},
                      {'prop': 'vmesh_method', 'text': 'Intersections'},
                      {'prop': 'use_clamp_overlap'},
                      {'prop': 'loop_slide'}]},
           {'id': 'shading',
            'label': 'Shading',
            'parent': None,
            'items': [{'prop': 'harden_normals'},
                      {'heading': 'Mark'},
                      {'prop': 'mark_seam', 'text': 'Seam'},
                      {'prop': 'mark_sharp', 'text': 'Sharp'},
                      {'prop': 'material'},
                      {'prop': 'face_strength_mode'}]}],
 'BOOLEAN': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'operation', 'expand': True},
                        {'prop': 'operand_type'},
                        {'prop': 'object'},
                        {'prop': 'collection'},
                        {'prop': 'solver', 'expand': True}]},
             {'id': 'solver_options',
              'label': 'Solver Options',
              'parent': None,
              'items': [{'prop': 'material_mode', 'text': 'Materials'},
                        {'prop': 'use_self'},
                        {'prop': 'use_hole_tolerant'},
                        {'prop': 'double_threshold'},
                        {'prop': 'debug_options'}]}],
 'BUILD': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'frame_start'},
                      {'prop': 'frame_duration'},
                      {'prop': 'use_reverse'}]},
           {'id': 'randomize',
            'label': '',
            'parent': None,
            'items': [{'prop': 'seed'}],
            'header': ['use_random_order']}],
 'CAST': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'cast_type'},
                     {'heading': 'Axis'},
                     {'prop': 'use_x'},
                     {'prop': 'use_y'},
                     {'prop': 'use_z'},
                     {'prop': 'factor'},
                     {'prop': 'radius'},
                     {'prop': 'size'},
                     {'prop': 'use_radius_as_size'},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'},
                     {'prop': 'object'},
                     {'prop': 'use_transform'}]}],
 'CLOTH': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'COLLISION': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'CORRECTIVE_SMOOTH': [{'id': '',
                        'label': '',
                        'parent': None,
                        'items': [{'prop': 'factor', 'text': 'Factor'},
                                  {'prop': 'iterations'},
                                  {'prop': 'scale'},
                                  {'prop': 'smooth_type'},
                                  {'vgroup': 'vertex_group',
                                   'invert': 'invert_vertex_group'},
                                  {'prop': 'use_only_smooth'},
                                  {'prop': 'use_pin_boundary'},
                                  {'prop': 'rest_source'}]}],
 'CURVE': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'object', 'text': 'Curve Object'},
                      {'prop': 'deform_axis'},
                      {'vgroup': 'vertex_group',
                       'invert': 'invert_vertex_group'}]}],
 'DATA_TRANSFER': [{'id': '',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'object', 'text': 'Source'},
                              {'prop': 'use_object_transform'},
                              {'prop': 'mix_mode'},
                              {'prop': 'mix_factor'},
                              {'vgroup': 'vertex_group',
                               'invert': 'invert_vertex_group'}]},
                   {'id': 'vertex',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'data_types_verts', 'expand': True},
                              {'prop': 'vert_mapping', 'text': 'Mapping'}],
                    'header': ['use_vert_data']},
                   {'id': 'vertex_vgroup',
                    'label': 'Vertex Groups',
                    'parent': 'vertex',
                    'items': [{'prop': 'layers_vgroup_select_src',
                               'text': 'Layer Selection'},
                              {'prop': 'layers_vgroup_select_dst',
                               'text': 'Layer Mapping'}]},
                   {'id': 'vert_vcol',
                    'label': 'Colors',
                    'parent': 'vertex',
                    'items': [{'prop': 'layers_vcol_vert_select_src',
                               'text': 'Layer Selection'},
                              {'prop': 'layers_vcol_vert_select_dst',
                               'text': 'Layer Mapping'}]},
                   {'id': 'edge',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'data_types_edges', 'expand': True},
                              {'prop': 'edge_mapping', 'text': 'Mapping'}],
                    'header': ['use_edge_data']},
                   {'id': 'face_corner',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'data_types_loops', 'expand': True},
                              {'prop': 'loop_mapping', 'text': 'Mapping'}],
                    'header': ['use_loop_data']},
                   {'id': 'face_corner_vcol',
                    'label': 'Colors',
                    'parent': 'face_corner',
                    'items': [{'prop': 'layers_vcol_loop_select_src',
                               'text': 'Layer Selection'},
                              {'prop': 'layers_vcol_loop_select_dst',
                               'text': 'Layer Mapping'}]},
                   {'id': 'face_corner_uv',
                    'label': 'UVs',
                    'parent': 'face_corner',
                    'items': [{'prop': 'layers_uv_select_src',
                               'text': 'Layer Selection'},
                              {'prop': 'layers_uv_select_dst',
                               'text': 'Layer Mapping'},
                              {'prop': 'islands_precision'}]},
                   {'id': 'face',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'data_types_polys'},
                              {'prop': 'poly_mapping', 'text': 'Mapping'}],
                    'header': ['use_poly_data']},
                   {'id': 'advanced',
                    'label': 'Topology Mapping',
                    'parent': None,
                    'items': [{'heading': 'Max Distance'},
                              {'prop': 'use_max_distance'},
                              {'prop': 'max_distance'},
                              {'prop': 'ray_radius'}]}],
 'DECIMATE': [{'id': '',
               'label': '',
               'parent': None,
               'items': [{'prop': 'decimate_type', 'expand': True},
                         {'prop': 'ratio', 'slider': True},
                         {'heading': 'Symmetry'},
                         {'prop': 'use_symmetry'},
                         {'prop': 'symmetry_axis', 'expand': True},
                         {'prop': 'use_collapse_triangulate'},
                         {'vgroup': 'vertex_group',
                          'invert': 'invert_vertex_group'},
                         {'prop': 'vertex_group_factor'},
                         {'prop': 'iterations'},
                         {'prop': 'angle_limit'},
                         {'prop': 'delimit'},
                         {'prop': 'use_dissolve_boundaries'}]}],
 'DISPLACE': [{'id': '',
               'label': '',
               'parent': None,
               'items': [{'prop': 'texture'},
                         {'prop': 'texture_coords', 'text': 'Coordinates'},
                         {'prop': 'texture_coords_object', 'text': 'Object'},
                         {'prop': 'texture_coords_bone', 'text': 'Bone'},
                         {'prop': 'uv_layer'},
                         {'sep': True},
                         {'prop': 'direction'},
                         {'prop': 'space'},
                         {'sep': True},
                         {'prop': 'strength'},
                         {'prop': 'mid_level'},
                         {'vgroup': 'vertex_group',
                          'invert': 'invert_vertex_group'}]}],
 'DYNAMIC_PAINT': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'EDGE_SPLIT': [{'id': '',
                 'label': '',
                 'parent': None,
                 'items': [{'heading': 'Edge Angle'},
                           {'prop': 'use_edge_angle'},
                           {'prop': 'split_angle'},
                           {'prop': 'use_edge_sharp',
                            'text': 'Sharp Edges'}]}],
 'EXPLODE': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'particle_uv'},
                        {'heading': 'Show'},
                        {'prop': 'show_alive'},
                        {'prop': 'show_dead'},
                        {'prop': 'show_unborn'},
                        {'prop': 'use_edge_cut'},
                        {'prop': 'use_size'},
                        {'vgroup': 'vertex_group',
                         'invert': 'invert_vertex_group'},
                        {'prop': 'protect'}]}],
 'FLUID': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'HOOK': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'object'},
                     {'prop': 'subtarget', 'text': 'Bone'},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'},
                     {'prop': 'strength', 'slider': True}]},
          {'id': 'falloff',
           'label': 'Falloff',
           'parent': None,
           'items': [{'prop': 'falloff_type', 'text': 'Type'},
                     {'prop': 'falloff_radius'},
                     {'prop': 'use_falloff_uniform'},
                     {'prop': 'falloff_curve'}]}],
 'LAPLACIANDEFORM': [{'id': '',
                      'label': '',
                      'parent': None,
                      'items': [{'prop': 'iterations'},
                                {'vgroup': 'vertex_group',
                                 'invert': 'invert_vertex_group'}]}],
 'LAPLACIANSMOOTH': [{'id': '',
                      'label': '',
                      'parent': None,
                      'items': [{'prop': 'iterations'},
                                {'heading': 'Axis'},
                                {'prop': 'use_x'},
                                {'prop': 'use_y'},
                                {'prop': 'use_z'},
                                {'prop': 'lambda_factor'},
                                {'prop': 'lambda_border'},
                                {'prop': 'use_volume_preserve'},
                                {'prop': 'use_normalized'},
                                {'vgroup': 'vertex_group',
                                 'invert': 'invert_vertex_group'}]}],
 'LATTICE': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'object'},
                        {'vgroup': 'vertex_group',
                         'invert': 'invert_vertex_group'},
                        {'prop': 'strength', 'slider': True}]}],
 'LINEART': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'use_cache'},
                        {'prop': 'source_type'},
                        {'prop': 'source_object'},
                        {'prop': 'source_collection'},
                        {'prop': 'use_invert_collection'},
                        {'prop': 'target_layer'},
                        {'prop': 'target_material'},
                        {'prop': 'radius',
                         'slider': True,
                         'text': 'Line Radius'},
                        {'prop': 'opacity', 'slider': True},
                        {'prop': 'fill_strokes'}]},
             {'id': 'edge_types',
              'label': 'Edge Types',
              'parent': None,
              'items': [{'prop': 'shadow_region_filtering',
                         'text': 'Illumination Filtering'},
                        {'heading': 'Create'},
                        {'prop': 'use_contour'},
                        {'prop': 'silhouette_filtering'},
                        {'prop': 'use_invert_silhouette'},
                        {'prop': 'use_crease',
                         'text': 'Crease (Angle Cached)'},
                        {'prop': 'crease_threshold', 'slider': True},
                        {'prop': 'use_intersection', 'text': 'Intersections'},
                        {'prop': 'use_material', 'text': 'Material Borders'},
                        {'prop': 'use_edge_mark', 'text': 'Edge Marks'},
                        {'prop': 'use_loose', 'text': 'Loose'},
                        {'prop': 'use_light_contour',
                         'text': 'Light Contour'},
                        {'prop': 'use_shadow', 'text': 'Cast Shadow'},
                        {'prop': 'use_overlap_edge_type_support',
                         'text': 'Allow Overlapping Types'}]},
             {'id': 'light_reference',
              'label': 'Light Reference',
              'parent': None,
              'items': [{'prop': 'light_contour_object'},
                        {'prop': 'shadow_camera_size'},
                        {'prop': 'shadow_camera_near', 'text': 'Near'},
                        {'prop': 'shadow_camera_far', 'text': 'Far'}]},
             {'id': 'geometry',
              'label': 'Geometry Processing',
              'parent': None,
              'items': [{'heading': 'Custom Camera'},
                        {'prop': 'use_custom_camera'},
                        {'prop': 'source_camera'},
                        {'prop': 'use_edge_overlap',
                         'text': 'Overlapping Edges As Contour'},
                        {'prop': 'use_object_instances'},
                        {'prop': 'use_clip_plane_boundaries'},
                        {'prop': 'use_crease_on_smooth',
                         'text': 'Crease On Smooth'},
                        {'prop': 'use_crease_on_sharp',
                         'text': 'Crease On Sharp'},
                        {'prop': 'use_back_face_culling',
                         'text': 'Force Backface Culling'}]},
             {'id': 'occlusion',
              'label': 'Occlusion',
              'parent': None,
              'items': [{'prop': 'use_multiple_levels', 'text': 'Range'},
                        {'prop': 'level_start'},
                        {'prop': 'level_end', 'text': 'End'}]},
             {'id': 'material_mask',
              'label': '',
              'parent': 'occlusion',
              'items': [{'heading': 'Masks'},
                        {'prop': 'use_material_mask_bits'},
                        {'prop': 'use_material_mask_match',
                         'text': 'Exact Match'}],
              'header': ['use_material_mask']},
             {'id': 'intersection',
              'label': 'Intersection',
              'parent': None,
              'items': [{'heading': 'Collection Masks'},
                        {'prop': 'use_intersection_mask'},
                        {'prop': 'use_intersection_match',
                         'text': 'Exact Match'}]},
             {'id': 'face_mark',
              'label': '',
              'parent': None,
              'items': [{'prop': 'use_face_mark_invert'},
                        {'prop': 'use_face_mark_boundaries'},
                        {'prop': 'use_face_mark_keep_contour'}],
              'header': ['use_face_mark']},
             {'id': 'chaining',
              'label': 'Chaining',
              'parent': None,
              'items': [{'heading': 'Chain'},
                        {'prop': 'use_fuzzy_intersections'},
                        {'prop': 'use_fuzzy_all'},
                        {'prop': 'use_loose_edge_chain',
                         'text': 'Loose Edges'},
                        {'prop': 'use_loose_as_contour',
                         'text': 'Loose Edges As Contour'},
                        {'prop': 'use_detail_preserve'},
                        {'prop': 'use_geometry_space_chain',
                         'text': 'Geometry Space'},
                        {'prop': 'chaining_image_threshold',
                         'text': 'Geometry Threshold'},
                        {'prop': 'smooth_tolerance', 'slider': True},
                        {'prop': 'split_angle', 'slider': True}]},
             {'id': 'vgroup',
              'label': 'Vertex Weight Transfer',
              'parent': None,
              'items': [{'prop': 'source_vertex_group',
                         'text': 'Filter Source'},
                        {'prop': 'invert_source_vertex_group'},
                        {'prop': 'use_output_vertex_group_match_by_name'},
                        {'prop': 'vertex_group', 'text': 'Target'}]},
             {'id': 'composition',
              'label': 'Composition',
              'parent': None,
              'items': [{'prop': 'overscan'},
                        {'prop': 'use_image_boundary_trimming'},
                        {'prop': 'stroke_depth_offset',
                         'text': 'Depth Offset'},
                        {'prop': 'use_offset_towards_custom_camera',
                         'text': 'Towards Custom Camera'}]},
             {'id': 'bake',
              'label': 'Bake',
              'parent': None,
              'items': [{'prop': 'is_baked',
                         'text': 'Continue Without Clearing'}]}],
 'MASK': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'mode', 'expand': True},
                     {'prop': 'armature'},
                     {'prop': 'invert_vertex_group'},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'},
                     {'prop': 'use_smooth'},
                     {'prop': 'threshold'}]}],
 'MESH_TO_VOLUME': [{'id': '',
                     'label': '',
                     'parent': None,
                     'items': [{'prop': 'object'},
                               {'prop': 'density'},
                               {'prop': 'interior_band_width'},
                               {'prop': 'resolution_mode'},
                               {'prop': 'voxel_amount'},
                               {'prop': 'voxel_size'}]}],
 'MESH_CACHE': [{'id': '',
                 'label': '',
                 'parent': None,
                 'items': [{'prop': 'cache_format'},
                           {'prop': 'filepath'},
                           {'prop': 'factor', 'slider': True},
                           {'prop': 'deform_mode'},
                           {'prop': 'interpolation'},
                           {'vgroup': 'vertex_group',
                            'invert': 'invert_vertex_group'}]},
                {'id': 'time_remapping',
                 'label': 'Time Remapping',
                 'parent': None,
                 'items': [{'prop': 'time_mode', 'expand': True},
                           {'prop': 'play_mode', 'expand': True},
                           {'prop': 'frame_start'},
                           {'prop': 'frame_scale'},
                           {'prop': 'eval_frame'},
                           {'prop': 'eval_time'},
                           {'prop': 'eval_factor'}]},
                {'id': 'axis_mapping',
                 'label': 'Axis Mapping',
                 'parent': None,
                 'items': [{'prop': 'forward_axis'},
                           {'prop': 'up_axis'},
                           {'prop': 'flip_axis', 'text': 'Flip Axis'}]}],
 'MESH_DEFORM': [{'id': '',
                  'label': '',
                  'parent': None,
                  'items': [{'prop': 'object'},
                            {'vgroup': 'vertex_group',
                             'invert': 'invert_vertex_group'},
                            {'prop': 'precision'},
                            {'prop': 'use_dynamic_bind'}]}],
 'MESH_SEQUENCE_CACHE': [{'id': '',
                          'label': '',
                          'parent': None,
                          'items': [{'prop': 'cache_file'},
                                    {'prop': 'object_path'},
                                    {'prop': 'read_data', 'expand': True},
                                    {'prop': 'use_vertex_interpolation'}]},
                         {'id': 'time',
                          'label': 'Time',
                          'parent': None,
                          'items': []},
                         {'id': 'velocity',
                          'label': 'Velocity',
                          'parent': None,
                          'items': [{'prop': 'velocity_scale'}]},
                         {'id': 'override_layers',
                          'label': 'Override Layers',
                          'parent': None,
                          'items': []}],
 'MIRROR': [{'id': '',
             'label': '',
             'parent': None,
             'items': [{'prop': 'use_axis', 'text': 'Axis'},
                       {'prop': 'use_bisect_axis', 'text': 'Bisect'},
                       {'prop': 'use_bisect_flip_axis', 'text': 'Flip'},
                       {'sep': True},
                       {'prop': 'mirror_object'},
                       {'prop': 'use_clip', 'text': 'Clipping'},
                       {'heading': 'Merge'},
                       {'prop': 'use_mirror_merge'},
                       {'prop': 'merge_threshold'},
                       {'prop': 'bisect_threshold',
                        'text': 'Bisect Distance'}]},
            {'id': 'data',
             'label': 'Data',
             'parent': None,
             'items': [{'heading': 'Mirror U'},
                       {'prop': 'use_mirror_u'},
                       {'prop': 'mirror_offset_u', 'slider': True},
                       {'heading': 'V'},
                       {'prop': 'use_mirror_v'},
                       {'prop': 'mirror_offset_v', 'slider': True},
                       {'prop': 'offset_u',
                        'slider': True,
                        'text': 'Offset U'},
                       {'prop': 'offset_v', 'slider': True, 'text': 'V'},
                       {'prop': 'use_mirror_vertex_groups',
                        'text': 'Vertex Groups'},
                       {'prop': 'use_mirror_udim', 'text': 'Flip UDIM'}]}],
 'MULTIRES': [{'id': '',
               'label': '',
               'parent': None,
               'items': [{'prop': 'levels', 'text': 'Levels Viewport'},
                         {'prop': 'sculpt_levels', 'text': 'Sculpt'},
                         {'prop': 'render_levels', 'text': 'Render'},
                         {'prop': 'use_sculpt_base_mesh',
                          'text': 'Sculpt Base Mesh'},
                         {'prop': 'show_only_control_edges'}]},
              {'id': 'subdivide',
               'label': 'Subdivision',
               'parent': None,
               'items': []},
              {'id': 'shape', 'label': 'Shape', 'parent': None, 'items': []},
              {'id': 'generate',
               'label': 'Generate',
               'parent': None,
               'items': [{'prop': 'filepath'}]},
              {'id': 'advanced',
               'label': 'Advanced',
               'parent': None,
               'items': [{'prop': 'quality'},
                         {'prop': 'uv_smooth'},
                         {'prop': 'boundary_smooth'},
                         {'prop': 'use_creases'},
                         {'prop': 'use_custom_normals'}]}],
 'NODES': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'NORMAL_EDIT': [{'id': '',
                  'label': '',
                  'parent': None,
                  'items': [{'prop': 'mode', 'expand': True},
                            {'prop': 'target'},
                            {'prop': 'use_direction_parallel'}]},
                 {'id': 'mix',
                  'label': 'Mix',
                  'parent': None,
                  'items': [{'prop': 'mix_mode'},
                            {'prop': 'mix_factor'},
                            {'vgroup': 'vertex_group',
                             'invert': 'invert_vertex_group'},
                            {'prop': 'mix_limit'},
                            {'prop': 'no_polynors_fix'}]},
                 {'id': 'offset',
                  'label': 'Offset',
                  'parent': None,
                  'items': [{'prop': 'offset'}]}],
 'OCEAN': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'geometry_mode'},
                      {'prop': 'repeat_x', 'text': 'Repeat X'},
                      {'prop': 'repeat_y', 'text': 'Y'},
                      {'prop': 'viewport_resolution',
                       'text': 'Resolution Viewport'},
                      {'prop': 'resolution', 'text': 'Render'},
                      {'prop': 'time'},
                      {'prop': 'depth'},
                      {'prop': 'size'},
                      {'prop': 'spatial_size'},
                      {'prop': 'random_seed'},
                      {'prop': 'use_normals'}]},
           {'id': 'waves',
            'label': 'Waves',
            'parent': None,
            'items': [{'prop': 'wave_scale', 'text': 'Scale'},
                      {'prop': 'wave_scale_min'},
                      {'prop': 'choppiness'},
                      {'prop': 'wind_velocity'},
                      {'sep': True},
                      {'prop': 'wave_alignment',
                       'slider': True,
                       'text': 'Alignment'},
                      {'prop': 'wave_direction', 'text': 'Direction'},
                      {'prop': 'damping'}]},
           {'id': 'foam',
            'label': '',
            'parent': None,
            'items': [{'prop': 'foam_layer_name', 'text': 'Data Layer'},
                      {'prop': 'foam_coverage', 'text': 'Coverage'}],
            'header': ['use_foam']},
           {'id': 'spray',
            'label': '',
            'parent': 'foam',
            'items': [{'prop': 'spray_layer_name', 'text': 'Data Layer'},
                      {'prop': 'invert_spray', 'text': 'Invert'}],
            'header': ['use_spray']},
           {'id': 'spectrum',
            'label': 'Spectrum',
            'parent': None,
            'items': [{'prop': 'spectrum'},
                      {'prop': 'sharpen_peak_jonswap', 'slider': True},
                      {'prop': 'fetch_jonswap'}]},
           {'id': 'bake',
            'label': 'Bake',
            'parent': None,
            'items': [{'prop': 'filepath'},
                      {'prop': 'frame_start', 'text': 'Frame Start'},
                      {'prop': 'frame_end', 'text': 'End'},
                      {'prop': 'bake_foam_fade'}]}],
 'PARTICLE_INSTANCE': [{'id': '',
                        'label': '',
                        'parent': None,
                        'items': [{'prop': 'object'},
                                  {'prop': 'particle_system',
                                   'text': 'Particle System'},
                                  {'prop': 'particle_system_index',
                                   'text': 'Particle System'},
                                  {'sep': True},
                                  {'heading': 'Create Instances'},
                                  {'prop': 'use_normal'},
                                  {'prop': 'use_children'},
                                  {'prop': 'use_size'},
                                  {'heading': 'Show'},
                                  {'prop': 'show_alive'},
                                  {'prop': 'show_dead'},
                                  {'prop': 'show_unborn'},
                                  {'prop': 'particle_amount',
                                   'text': 'Amount'},
                                  {'prop': 'particle_offset',
                                   'text': 'Offset'},
                                  {'sep': True},
                                  {'prop': 'space',
                                   'text': 'Coordinate Space'},
                                  {'prop': 'axis', 'expand': True}]},
                       {'id': 'paths',
                        'label': '',
                        'parent': None,
                        'items': [{'prop': 'position', 'slider': True},
                                  {'prop': 'random_position',
                                   'slider': True,
                                   'text': 'Random'},
                                  {'prop': 'rotation', 'slider': True},
                                  {'prop': 'random_rotation',
                                   'slider': True,
                                   'text': 'Random'},
                                  {'prop': 'use_preserve_shape'}],
                        'header': ['use_path']},
                       {'id': 'layers',
                        'label': 'Layers',
                        'parent': None,
                        'items': [{'prop': 'index_layer_name',
                                   'text': 'Index'},
                                  {'prop': 'value_layer_name',
                                   'text': 'Value'}]}],
 'PARTICLE_SYSTEM': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'REMESH': [{'id': '',
             'label': '',
             'parent': None,
             'items': [{'prop': 'mode', 'expand': True},
                       {'prop': 'voxel_size'},
                       {'prop': 'adaptivity'},
                       {'prop': 'octree_depth'},
                       {'prop': 'scale'},
                       {'prop': 'sharpness'},
                       {'prop': 'use_remove_disconnected'},
                       {'prop': 'threshold'},
                       {'prop': 'use_smooth_shade'}]}],
 'SCREW': [{'id': '',
            'label': '',
            'parent': None,
            'items': [{'prop': 'angle'},
                      {'prop': 'screw_offset'},
                      {'prop': 'iterations'},
                      {'sep': True},
                      {'prop': 'axis', 'expand': True},
                      {'prop': 'object', 'text': 'Axis Object'},
                      {'prop': 'use_object_screw_offset'},
                      {'sep': True},
                      {'prop': 'steps', 'text': 'Steps Viewport'},
                      {'prop': 'render_steps', 'text': 'Render'},
                      {'sep': True},
                      {'heading': 'Merge'},
                      {'prop': 'use_merge_vertices'},
                      {'prop': 'merge_threshold'},
                      {'sep': True},
                      {'heading': 'Stretch UVs'},
                      {'prop': 'use_stretch_u', 'text': 'U'},
                      {'prop': 'use_stretch_v', 'text': 'V'}]},
           {'id': 'normals',
            'label': 'Normals',
            'parent': None,
            'items': [{'prop': 'use_smooth_shade'},
                      {'prop': 'use_normal_calculate'},
                      {'prop': 'use_normal_flip'}]}],
 'SHRINKWRAP': [{'id': '',
                 'label': '',
                 'parent': None,
                 'items': [{'prop': 'wrap_method'},
                           {'prop': 'wrap_mode'},
                           {'prop': 'project_limit', 'text': 'Limit'},
                           {'prop': 'subsurf_levels'},
                           {'heading': 'Axis'},
                           {'prop': 'use_project_x'},
                           {'prop': 'use_project_y'},
                           {'prop': 'use_project_z'},
                           {'prop': 'use_negative_direction'},
                           {'prop': 'use_positive_direction'},
                           {'prop': 'cull_face', 'expand': True},
                           {'prop': 'use_invert_cull'},
                           {'prop': 'target'},
                           {'prop': 'auxiliary_target'},
                           {'prop': 'offset'},
                           {'vgroup': 'vertex_group',
                            'invert': 'invert_vertex_group'}]}],
 'SIMPLE_DEFORM': [{'id': '',
                    'label': '',
                    'parent': None,
                    'items': [{'prop': 'deform_method', 'expand': True},
                              {'prop': 'factor'},
                              {'prop': 'angle'},
                              {'prop': 'origin'},
                              {'prop': 'deform_axis', 'expand': True}]},
                   {'id': 'restrictions',
                    'label': 'Restrictions',
                    'parent': None,
                    'items': [{'prop': 'limits', 'slider': True},
                              {'heading': 'Lock'},
                              {'prop': 'lock_x'},
                              {'prop': 'lock_y'},
                              {'prop': 'lock_z'},
                              {'vgroup': 'vertex_group',
                               'invert': 'invert_vertex_group'}]}],
 'SKIN': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'branch_smoothing'},
                     {'heading': 'Symmetry'},
                     {'prop': 'use_x_symmetry'},
                     {'prop': 'use_y_symmetry'},
                     {'prop': 'use_z_symmetry'},
                     {'prop': 'use_smooth_shade'}]}],
 'SMOOTH': [{'id': '',
             'label': '',
             'parent': None,
             'items': [{'heading': 'Axis'},
                       {'prop': 'use_x'},
                       {'prop': 'use_y'},
                       {'prop': 'use_z'},
                       {'prop': 'factor'},
                       {'prop': 'iterations'},
                       {'vgroup': 'vertex_group',
                        'invert': 'invert_vertex_group'}]}],
 'SOFT_BODY': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'SOLIDIFY': [{'id': '',
               'label': '',
               'parent': None,
               'items': [{'prop': 'solidify_mode'},
                         {'prop': 'nonmanifold_thickness_mode',
                          'text': 'Thickness Mode'},
                         {'prop': 'nonmanifold_boundary_mode',
                          'text': 'Boundary'},
                         {'prop': 'thickness'},
                         {'prop': 'offset'},
                         {'prop': 'nonmanifold_merge_threshold'},
                         {'prop': 'use_even_offset'},
                         {'heading': 'Rim'},
                         {'prop': 'use_rim', 'text': 'Fill'},
                         {'prop': 'use_rim_only'},
                         {'sep': True},
                         {'vgroup': 'vertex_group',
                          'invert': 'invert_vertex_group'},
                         {'prop': 'thickness_vertex_group', 'text': 'Factor'},
                         {'prop': 'use_flat_faces'}]},
              {'id': 'normals',
               'label': 'Normals',
               'parent': None,
               'items': [{'prop': 'use_flip_normals', 'text': 'Flip'},
                         {'prop': 'use_quality_normals',
                          'text': 'High Quality'}]},
              {'id': 'materials',
               'label': 'Materials',
               'parent': None,
               'items': [{'prop': 'material_offset'},
                         {'prop': 'material_offset_rim', 'text': 'Rim'}]},
              {'id': 'edge_data',
               'label': 'Edge Data',
               'parent': None,
               'items': [{'prop': 'edge_crease_inner',
                          'text': 'Crease Inner'},
                         {'prop': 'edge_crease_outer', 'text': 'Outer'},
                         {'prop': 'edge_crease_rim', 'text': 'Rim'},
                         {'prop': 'bevel_convex', 'slider': True}]},
              {'id': 'clamp',
               'label': 'Thickness Clamp',
               'parent': None,
               'items': [{'prop': 'thickness_clamp'},
                         {'prop': 'use_thickness_angle_clamp'}]},
              {'id': 'vertex_groups',
               'label': 'Output Vertex Groups',
               'parent': None,
               'items': [{'prop': 'shell_vertex_group', 'text': 'Shell'},
                         {'prop': 'rim_vertex_group', 'text': 'Rim'}]}],
 'SUBSURF': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'subdivision_type', 'expand': True},
                        {'prop': 'levels', 'text': 'Levels Viewport'},
                        {'prop': 'render_levels', 'text': 'Render'},
                        {'prop': 'show_only_control_edges'},
                        {'prop': 'adaptive_space', 'text': 'Space'},
                        {'prop': 'adaptive_object_edge_length'},
                        {'prop': 'adaptive_pixel_size'},
                        {'prop': 'use_limit_surface'},
                        {'prop': 'quality'},
                        {'prop': 'uv_smooth'},
                        {'prop': 'boundary_smooth'},
                        {'prop': 'use_creases'},
                        {'prop': 'use_custom_normals'}]}],
 'SURFACE': [{'id': '', 'label': '', 'parent': None, 'items': []}],
 'SURFACE_DEFORM': [{'id': '',
                     'label': '',
                     'parent': None,
                     'items': [{'prop': 'target'},
                               {'prop': 'falloff'},
                               {'prop': 'strength'},
                               {'vgroup': 'vertex_group',
                                'invert': 'invert_vertex_group'},
                               {'prop': 'use_sparse_bind'}]}],
 'TRIANGULATE': [{'id': '',
                  'label': '',
                  'parent': None,
                  'items': [{'prop': 'quad_method'},
                            {'prop': 'ngon_method'},
                            {'prop': 'min_vertices'},
                            {'prop': 'keep_custom_normals'}]}],
 'UV_PROJECT': [{'id': '',
                 'label': '',
                 'parent': None,
                 'items': [{'prop': 'uv_layer'},
                           {'prop': 'aspect_x'},
                           {'prop': 'aspect_y', 'text': 'Y'},
                           {'prop': 'scale_x'},
                           {'prop': 'scale_y', 'text': 'Y'},
                           {'prop': 'projector_count',
                            'text': 'Projectors'}]}],
 'UV_WARP': [{'id': '',
              'label': '',
              'parent': None,
              'items': [{'prop': 'uv_layer'},
                        {'prop': 'center'},
                        {'prop': 'axis_u', 'text': 'Axis U'},
                        {'prop': 'axis_v', 'text': 'V'},
                        {'prop': 'object_from'},
                        {'prop': 'bone_from'},
                        {'prop': 'object_to', 'text': 'To'},
                        {'prop': 'bone_to'},
                        {'vgroup': 'vertex_group',
                         'invert': 'invert_vertex_group'}]},
             {'id': 'offset',
              'label': 'Transform',
              'parent': None,
              'items': [{'prop': 'offset'},
                        {'prop': 'scale'},
                        {'prop': 'rotation'}]}],
 'VOLUME_DISPLACE': [{'id': '',
                      'label': '',
                      'parent': None,
                      'items': [{'prop': 'texture'},
                                {'prop': 'texture_map_mode',
                                 'text': 'Texture Mapping'},
                                {'prop': 'texture_map_object',
                                 'text': 'Object'},
                                {'prop': 'strength'},
                                {'prop': 'texture_sample_radius',
                                 'text': 'Sample Radius'},
                                {'prop': 'texture_mid_level',
                                 'text': 'Mid Level'}]}],
 'VOLUME_TO_MESH': [{'id': '',
                     'label': '',
                     'parent': None,
                     'items': [{'prop': 'object'},
                               {'prop': 'grid_name'},
                               {'prop': 'resolution_mode'},
                               {'prop': 'voxel_amount'},
                               {'prop': 'voxel_size'},
                               {'prop': 'threshold'},
                               {'prop': 'adaptivity'},
                               {'prop': 'use_smooth_shade'}]}],
 'WARP': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'object_from'},
                     {'prop': 'bone_from', 'text': 'Bone'},
                     {'prop': 'object_to'},
                     {'prop': 'bone_to', 'text': 'Bone'},
                     {'prop': 'use_volume_preserve'},
                     {'prop': 'strength'},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'}]},
          {'id': 'falloff',
           'label': 'Falloff',
           'parent': None,
           'items': [{'prop': 'falloff_type'},
                     {'prop': 'falloff_radius'},
                     {'prop': 'falloff_curve'}]},
          {'id': 'texture',
           'label': 'Texture',
           'parent': None,
           'items': [{'prop': 'texture'},
                     {'prop': 'texture_coords', 'text': 'Coordinates'},
                     {'prop': 'texture_coords_object', 'text': 'Object'},
                     {'prop': 'texture_coords_bone', 'text': 'Bone'},
                     {'prop': 'uv_layer'}]}],
 'WAVE': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'heading': 'Motion'},
                     {'prop': 'use_x'},
                     {'prop': 'use_y'},
                     {'prop': 'use_cyclic'},
                     {'heading': 'Along Normals'},
                     {'prop': 'use_normal'},
                     {'prop': 'use_normal_x', 'text': 'X'},
                     {'prop': 'use_normal_y', 'text': 'Y'},
                     {'prop': 'use_normal_z', 'text': 'Z'},
                     {'prop': 'falloff_radius', 'text': 'Falloff'},
                     {'prop': 'height', 'slider': True},
                     {'prop': 'width', 'slider': True},
                     {'prop': 'narrowness', 'slider': True},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'}]},
          {'id': 'position',
           'label': 'Start Position',
           'parent': None,
           'items': [{'prop': 'start_position_object', 'text': 'Object'},
                     {'prop': 'start_position_x', 'text': 'Start Position X'},
                     {'prop': 'start_position_y', 'text': 'Y'}]},
          {'id': 'time',
           'label': 'Time',
           'parent': None,
           'items': [{'prop': 'time_offset', 'text': 'Offset'},
                     {'prop': 'lifetime', 'text': 'Life'},
                     {'prop': 'damping_time', 'text': 'Damping'},
                     {'prop': 'speed', 'slider': True}]},
          {'id': 'texture',
           'label': 'Texture',
           'parent': None,
           'items': [{'prop': 'texture'},
                     {'prop': 'texture_coords', 'text': 'Coordinates'},
                     {'prop': 'texture_coords_object', 'text': 'Object'},
                     {'prop': 'texture_coords_bone', 'text': 'Bone'},
                     {'prop': 'uv_layer'}]}],
 'WEIGHTED_NORMAL': [{'id': '',
                      'label': '',
                      'parent': None,
                      'items': [{'prop': 'mode'},
                                {'prop': 'weight', 'text': 'Weight'},
                                {'prop': 'thresh', 'text': 'Threshold'},
                                {'prop': 'keep_sharp'},
                                {'prop': 'use_face_influence'},
                                {'vgroup': 'vertex_group',
                                 'invert': 'invert_vertex_group'}]}],
 'VERTEX_WEIGHT_EDIT': [{'id': '',
                         'label': '',
                         'parent': None,
                         'items': [{'prop': 'vertex_group'},
                                   {'prop': 'default_weight', 'slider': True},
                                   {'heading': 'Group Add'},
                                   {'prop': 'use_add'},
                                   {'prop': 'add_threshold',
                                    'slider': True,
                                    'text': 'Threshold'},
                                   {'heading': 'Group Remove'},
                                   {'prop': 'use_remove'},
                                   {'prop': 'remove_threshold',
                                    'slider': True,
                                    'text': 'Threshold'},
                                   {'prop': 'normalize'}]},
                        {'id': 'falloff',
                         'label': 'Falloff',
                         'parent': None,
                         'items': [{'prop': 'falloff_type', 'text': 'Type'},
                                   {'prop': 'invert_falloff'},
                                   {'prop': 'map_curve'}]},
                        {'id': 'influence',
                         'label': 'Influence',
                         'parent': None,
                         'items': [{'prop': 'mask_constant',
                                    'slider': True,
                                    'text': 'Global Influence:'},
                                   {'vgroup': 'mask_vertex_group',
                                    'invert': 'invert_mask_vertex_group'},
                                   {'prop': 'mask_texture'},
                                   {'prop': 'mask_tex_use_channel',
                                    'text': 'Channel'},
                                   {'prop': 'mask_tex_mapping'},
                                   {'prop': 'mask_tex_map_object',
                                    'text': 'Object'},
                                   {'prop': 'mask_tex_uv_layer'}]}],
 'VERTEX_WEIGHT_MIX': [{'id': '',
                        'label': '',
                        'parent': None,
                        'items': [{'vgroup': 'vertex_group_a',
                                   'invert': 'invert_vertex_group_a'},
                                  {'vgroup': 'vertex_group_b',
                                   'invert': 'invert_vertex_group_b'},
                                  {'sep': True},
                                  {'prop': 'default_weight_a'},
                                  {'prop': 'default_weight_b', 'text': 'B'},
                                  {'sep': True},
                                  {'prop': 'mix_set'},
                                  {'prop': 'mix_mode'},
                                  {'prop': 'normalize'}]},
                       {'id': 'influence',
                        'label': 'Influence',
                        'parent': None,
                        'items': [{'prop': 'mask_constant',
                                   'slider': True,
                                   'text': 'Global Influence:'},
                                  {'vgroup': 'mask_vertex_group',
                                   'invert': 'invert_mask_vertex_group'},
                                  {'prop': 'mask_texture'},
                                  {'prop': 'mask_tex_use_channel',
                                   'text': 'Channel'},
                                  {'prop': 'mask_tex_mapping'},
                                  {'prop': 'mask_tex_map_object',
                                   'text': 'Object'},
                                  {'prop': 'mask_tex_uv_layer'}]}],
 'VERTEX_WEIGHT_PROXIMITY': [{'id': '',
                              'label': '',
                              'parent': None,
                              'items': [{'prop': 'vertex_group'},
                                        {'prop': 'target'},
                                        {'sep': True},
                                        {'prop': 'proximity_mode'},
                                        {'prop': 'proximity_geometry',
                                         'expand': True,
                                         'text': 'Geometry'},
                                        {'prop': 'min_dist'},
                                        {'prop': 'max_dist'},
                                        {'prop': 'normalize'}]},
                             {'id': 'falloff',
                              'label': 'Falloff',
                              'parent': None,
                              'items': [{'prop': 'falloff_type',
                                         'text': 'Type'},
                                        {'prop': 'invert_falloff'},
                                        {'prop': 'map_curve'}]},
                             {'id': 'influence',
                              'label': 'Influence',
                              'parent': None,
                              'items': [{'prop': 'mask_constant',
                                         'slider': True,
                                         'text': 'Global Influence:'},
                                        {'vgroup': 'mask_vertex_group',
                                         'invert': 'invert_mask_vertex_group'},
                                        {'prop': 'mask_texture'},
                                        {'prop': 'mask_tex_use_channel',
                                         'text': 'Channel'},
                                        {'prop': 'mask_tex_mapping'},
                                        {'prop': 'mask_tex_map_object',
                                         'text': 'Object'},
                                        {'prop': 'mask_tex_uv_layer'}]}],
 'WELD': [{'id': '',
           'label': '',
           'parent': None,
           'items': [{'prop': 'mode'},
                     {'prop': 'merge_threshold', 'text': 'Distance'},
                     {'prop': 'loose_edges'},
                     {'vgroup': 'vertex_group',
                      'invert': 'invert_vertex_group'}]}],
 'WIREFRAME': [{'id': '',
                'label': '',
                'parent': None,
                'items': [{'prop': 'thickness', 'text': 'Thickness'},
                          {'prop': 'offset'},
                          {'prop': 'use_boundary', 'text': 'Boundary'},
                          {'prop': 'use_replace', 'text': 'Replace Original'},
                          {'heading': 'Thickness'},
                          {'prop': 'use_even_offset', 'text': 'Even'},
                          {'prop': 'use_relative_offset', 'text': 'Relative'},
                          {'heading': 'Crease Edges'},
                          {'prop': 'use_crease'},
                          {'prop': 'crease_weight', 'slider': True},
                          {'prop': 'material_offset',
                           'text': 'Material Offset'}]},
               {'id': 'vertex_group',
                'label': 'Vertex Group',
                'parent': None,
                'items': [{'vgroup': 'vertex_group',
                           'invert': 'invert_vertex_group'},
                          {'prop': 'thickness_vertex_group',
                           'text': 'Factor'}]}]}
