keys_user = [
    ('iops.esc',                        'ESC',              'PRESS', False, False, False),
    ('iops.f1',                         'F1',               'PRESS', False, False, False),
    ('iops.f2',                         'F2',               'PRESS', False, False, False),
    ('iops.f3',                         'F3',               'PRESS', False, False, False),
    ('iops.f4',                         'F4',               'PRESS', False, False, False),
    ('iops.f5',                         'F5',               'PRESS', False, False, False),
    ('iops.align_origin_to_normal',     'F5',               'PRESS', False, True, False),
    ('iops.to_verts',                   'F1',               'PRESS', False, True, False),
    ('iops.to_edges',                   'F2',               'PRESS', False, True, False),
    ('iops.to_faces',                   'F3',               'PRESS', False, True, False),
    ('iops.object_rotate_z',            'RIGHT_ARROW',      'PRESS', False, False, False),
    ('iops.object_rotate_mz',           'RIGHT_ARROW',      'PRESS', False, False, True),
    ('iops.object_rotate_y',            'DOWN_ARROW',       'PRESS', False, False, False),
    ('iops.object_rotate_my',           'DOWN_ARROW',       'PRESS', False, False, True),
    ('iops.object_rotate_x',            'LEFT_ARROW',       'PRESS', False, False, False),
    ('iops.object_rotate_mx',           'LEFT_ARROW',       'PRESS', False, False, True),
    ('iops.object_normalize',           'UP_ARROW',         'PRESS', False, False, False),
    ('iops.mesh_to_grid',               'UP_ARROW',         'PRESS', False, False, False),
    ('iops.modal_three_point_rotation', 'R',                'PRESS', True, True, True),
    ('iops.call_tps_panel',             'BUTTON4MOUSE',     'PRESS', False, False, True),
    ('iops.call_tm_panel',              'T',                'PRESS', True, True, True),
    ('iops.call_pie_menu',              'Q',                'PRESS', True, True, True),
    # Zaloopok's operators
    ('iops.z_grow_loop',                'F18',                'PRESS', True, True, True),
    ('iops.z_shrink_loop',              'F18',                'PRESS', True, True, True),
    ('iops.z_grow_ring',                'F18',                'PRESS', True, True, True),
    ('iops.z_shrink_ring',              'F18',                'PRESS', True, True, True),
    ('iops.z_delete_mode',              'F18',                'PRESS', True, True, True),
    ('iops.eq_edges',                   'F18',                'PRESS', True, True, True),
    ('iops.line_up_edges',              'F18',                'PRESS', True, True, True),
    ('iops.z_connect',                  'F18',                'PRESS', True, True, True),
    ('iops.z_put_on',                   'F18',                'PRESS', True, True, True),
    ('iops.z_mirror',                   'F18',                'PRESS', True, True, True),
    ('iops.z_select_bounded_ring',      'F18',                'PRESS', True, True, True),
    ('iops.z_select_bounded_loop',      'F18',                'PRESS', True, True, True),
]